sudo: required
before_install:
  - sudo apt-get install build-essential
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
#install: 
#    - make get-deps
script:
    - cd src 
    - make
    - ./helloworld
deploy:
  provider: releases
  api_key: 
    secure: "0980b7824e432f72a40b50a085ce26e63d94404f"
  file: "helloworld"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
